apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: alb-ingress-controller
imageTags:
  - name: docker.io/amazon/aws-alb-ingress-controller
    newTag: v1.1.2
namespace: kube-system
resources:
  - alb-ingress-controller.yaml
  - rbac-role.yaml