apiVersion: v1
data:
  dex.github.clientSecret: pzpp0/NK5C14cZUqkIVJjTAVsoZvQ0oSUB5+v6OkBye+tlyqFj815Kxb+7QYDtjG1+OpK08b8Qg7LCFz/L888AHJzNA0G3/pSCtHUOM0WJtXOh3bYu1A77s0yVlDAzeY.m5e87E6vTQEpYqUD.H6FmkH++0AcOCjZkxmGIAQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
# kubesec:v:3
# kubesec:aws:arn:aws:kms:ap-northeast-1:206574590278:key/5ba14cc9-fbeb-4153-aba7-722da1841b2e:AQICAHjdOVXjsaReAXg2dv/e6kKIXbprp+mMoO2qrE5GQDFnmgEeMc3UzmUPwiv8tvEw4jFkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzzDijTWKOKTecdHqAgEQgDt1Arhm3TVPykXJX53cKqJyhIHLj51gwAiSiYSNp62vHnEPvWvIKeg7umA/XPAAM/FEXjt34TaZFfYbMg==
# kubesec:mac:VwM9C/Nt/W0QNdU4.fPiQq9dkasE1HpNqBfKnQA==
