apiVersion: v1
data:
  dex.github.clientSecret: eG3J+8ao1rIYzt2zxBujdqLRqZcB/hw5Vt83bsToJQ4ElXTUdseFmq7mP2g4FqzGk2Cpq6btgWP1CoBOvAu5bCUniiIm9Fnh+AquFQ/dtPEncmkj5qYBcVnMKvvq9aU2.CXUu/bZNkLBkhYMi.f3Cw9rBq1+qcliJLElqa3g==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
# kubesec:v:3
# kubesec:aws:arn:aws:kms:ap-northeast-1:206574590278:key/5ba14cc9-fbeb-4153-aba7-722da1841b2e:AQICAHjdOVXjsaReAXg2dv/e6kKIXbprp+mMoO2qrE5GQDFnmgGKn6k1Q0bMlMpNx7cL/g3NAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMm+S7bpTSiW/4JCUiAgEQgDv9Pghf8s8HmT+ORzrdO/Iz7IzTUO5ODD7OjNrmwaRIQAZxrS+KOGK1mY1PZtpqnFuWhzkV3fxAbr32lw==
# kubesec:mac:NmDp7TIlOZ0zC0pN.lGXFdyMFqoa2Yy9eUkUB/w==
