apiVersion: v1
data:
  dex.github.clientSecret: Dv/GY8mRO/BXBq2E5/TlwHBXC7txFFyAMN1c6Eiytu7GF6dbcyNuVd6FaYpQYTwvyCQ2obvjBFUvjvF6e+oMVFXRfrmSEkPhEh48G+QB9LusH5JoR0BJKk6QYR2B/WLO.nkAyxgdVNHCO9YZI.yYSUCnNk8F8MuN+qvFv2kA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
# kubesec:v:3
# kubesec:aws:arn:aws:kms:ap-northeast-1:206574590278:key/5ba14cc9-fbeb-4153-aba7-722da1841b2e:AQICAHjdOVXjsaReAXg2dv/e6kKIXbprp+mMoO2qrE5GQDFnmgE2KdtEbPAXJxKOkQ38pItAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMd7iJF7MK+bs2skLlAgEQgDsQKF7TQKhHyO+Pv5s1aZQpFiKUxNaQe1QZOmKgkOMnkpTuZhzX4TqDfFlTbKSXsBh+dFxu1Bi0UtIo0Q==
# kubesec:mac:I1vcBZSMnKKpclSe.s12Bk3X3aZVrzB7G4Pe6yA==

