apiVersion: v1
data:
  dex.github.clientSecret: Dv/GY8mRO/BXBq2E5/TlwHBXC7txFFyAMN1c6Eiytu7GF6dbcyNuVd6FaYpQYTwvyCQ2obvjBFUvjvF6e+oMVFXRfrmSEkPhEh48G+QB9LusH5JoR0BJKk6QYR2B/WLO.nkAyxgdVNHCO9YZI.yYSUCnNk8F8MuN+qvFv2kA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
