apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/aws-alb-ingress-controller/
    repoURL: https://github.com/kmd2kmd/aws-cdk-eks
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
