apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v1.2.0
resources:
  - ingress/ingress.yaml
  - secret/argocd-secret.yaml
patchesStrategicMerge:
  - configmap/argocd-cm.yaml
  - deployment/deployment.yaml
namespace: argocd
