apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/kmd2kmd/aws-cdk-eks.git
  url: https://argocd.eks-mokumoku.rkato.classmethod.info
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 44df0b1c557039e25ad8
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: classmethod