apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application/kube-system/root/application.yaml
#  - application/microservices/root/application.yaml
  - appproject/appproject.yaml
