apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.5.14
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=eks-mokumoku.rkato.classmethod.info
            - --provider=aws
            - --policy=upsert-only